// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLogFolder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddLogFolder'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateProfile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function GetActiveProfileName() {
  return window['go']['main']['App']['GetActiveProfileName']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetLogFolders() {
  return window['go']['main']['App']['GetLogFolders']();
}

export function GetVisibleCount() {
  return window['go']['main']['App']['GetVisibleCount']();
}

export function GetWindowPosition() {
  return window['go']['main']['App']['GetWindowPosition']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenInEditor'](arg1, arg2);
}

export function RemoveLogFolder(arg1, arg2) {
  return window['go']['main']['App']['RemoveLogFolder'](arg1, arg2);
}

export function RestartHTTPServer() {
  return window['go']['main']['App']['RestartHTTPServer']();
}

export function RestartLogWatcher() {
  return window['go']['main']['App']['RestartLogWatcher']();
}

export function SaveFrontendConfig(arg1) {
  return window['go']['main']['App']['SaveFrontendConfig'](arg1);
}

export function SaveWindowPosition() {
  return window['go']['main']['App']['SaveWindowPosition']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartLogWatcher() {
  return window['go']['main']['App']['StartLogWatcher']();
}

export function StopLogWatcher() {
  return window['go']['main']['App']['StopLogWatcher']();
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function TestUpdateCheck() {
  return window['go']['main']['App']['TestUpdateCheck']();
}

export function ToggleLogFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleLogFolder'](arg1, arg2, arg3);
}

export function UpdateLogFolder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateLogFolder'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateProfile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateVisibleCount(arg1) {
  return window['go']['main']['App']['UpdateVisibleCount'](arg1);
}
