// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVisibleCount() {
  return window['go']['main']['App']['GetVisibleCount']();
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenInEditor'](arg1, arg2);
}

export function SaveFrontendConfig(arg1) {
  return window['go']['main']['App']['SaveFrontendConfig'](arg1);
}

export function UpdateVisibleCount(arg1) {
  return window['go']['main']['App']['UpdateVisibleCount'](arg1);
}
