// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLogFolder(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>,arg5:string):Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CreateProfile(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function GetActiveProfileName():Promise<string>;

export function GetConfig():Promise<main.Profile>;

export function GetCurrentVersion():Promise<string>;

export function GetLogFolders():Promise<Array<main.LogFolder>>;

export function GetVisibleCount():Promise<number>;

export function GetWindowPosition():Promise<main.WindowPosition>;

export function ListProfiles():Promise<Array<main.Profile>>;

export function OpenInEditor(arg1:string,arg2:number):Promise<void>;

export function RemoveLogFolder(arg1:string,arg2:string):Promise<void>;

export function RestartHTTPServer():Promise<void>;

export function RestartLogWatcher():Promise<void>;

export function SaveFrontendConfig(arg1:Record<string, any>):Promise<void>;

export function SaveWindowPosition():Promise<void>;

export function SelectFolder():Promise<string>;

export function StartLogWatcher():Promise<void>;

export function StopLogWatcher():Promise<void>;

export function SwitchProfile(arg1:string):Promise<void>;

export function TestUpdateCheck():Promise<main.UpdateInfo>;

export function ToggleLogFolder(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UpdateLogFolder(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>,arg5:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function UpdateVisibleCount(arg1:number):Promise<void>;
