// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetCurrentVersion():Promise<string>;

export function GetVisibleCount():Promise<number>;

export function OpenInEditor(arg1:string,arg2:number):Promise<void>;

export function SaveFrontendConfig(arg1:Record<string, any>):Promise<void>;

export function UpdateVisibleCount(arg1:number):Promise<void>;
