name: Simple Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: app/go.sum
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/frontend/package-lock.json
      
      - name: Build
        shell: bash
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.2
          cd app/frontend
          npm install
          cd ..
          wails build -platform windows/amd64 -nsis=false -webview2=embed
          mv build/bin/app.exe build/bin/versaDumps.exe
          cp config.yml build/bin/
          
      - name: Package
        shell: pwsh
        run: |
          cd app/build/bin
          Compress-Archive -Path versaDumps.exe, config.yml -DestinationPath ../../../versaDumps-windows-amd64.zip
          
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: versaDumps-windows-amd64.zip

  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: app/go.sum
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/frontend/package-lock.json
      
      - name: Build
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.2
          cd app/frontend
          npm install
          cd ..
          wails build -platform darwin/amd64
          cp config.yml build/bin/
          echo "Contents of build/bin:"
          ls -la build/bin/
          
      - name: Package
        run: |
          cd app/build/bin
          # En macOS, Wails crea un .app bundle
          if [ -d "app.app" ]; then
            mv app.app versaDumps.app
            tar -czf ../../../versaDumps-macos-amd64.tar.gz versaDumps.app config.yml
          elif [ -f "app" ]; then
            mv app versaDumps
            tar -czf ../../../versaDumps-macos-amd64.tar.gz versaDumps config.yml
          else
            echo "Error: No se encontró el ejecutable"
            exit 1
          fi
          
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: versaDumps-macos-amd64.tar.gz

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: app/go.sum
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          # Install GTK and build tools
          sudo apt-get install -y libgtk-3-dev build-essential pkg-config
          
          # Check which webkit package is available and install it
          if apt-cache search --names-only '^libwebkit2gtk-4.0-dev$' | grep -q libwebkit2gtk-4.0-dev; then
            echo "Installing libwebkit2gtk-4.0-dev"
            sudo apt-get install -y libwebkit2gtk-4.0-dev
          elif apt-cache search --names-only '^libwebkit2gtk-4.1-dev$' | grep -q libwebkit2gtk-4.1-dev; then
            echo "Installing libwebkit2gtk-4.1-dev"
            sudo apt-get install -y libwebkit2gtk-4.1-dev
            # Try to create a symlink for compatibility
            if [ -f /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc ]; then
              sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc
            fi
          else
            echo "ERROR: No suitable webkit2gtk package found"
            echo "Available webkit packages:"
            apt-cache search webkit2gtk
            exit 1
          fi
      
      - name: Build
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.2
          cd app/frontend
          npm install
          cd ..
          wails build -platform linux/amd64
          mv build/bin/app build/bin/versaDumps
          cp config.yml build/bin/
          
      - name: Package
        run: |
          cd app/build/bin
          tar -czf ../../../versaDumps-linux-amd64.tar.gz versaDumps config.yml
          
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: versaDumps-linux-amd64.tar.gz

  release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: windows-build
      
      - uses: actions/download-artifact@v4
        with:
          name: macos-build
      
      - uses: actions/download-artifact@v4
        with:
          name: linux-build
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            versaDumps-windows-amd64.zip
            versaDumps-macos-amd64.tar.gz
            versaDumps-linux-amd64.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
